@isTest
public class TestAccountActivationHandler {
    @isTest
    static void testDefaultContactCreation() {
        // Create a test Account with Type = 'Customer' and IsActive = true
        Account testAccount = new Account(
            Name = 'Test',
            Type = 'Customer - Direct',
            AGActive__c = true
        );
        insert testAccount;

        // Verify that a default contact is created
        List<Contact> createdContacts = [SELECT Id FROM Contact WHERE AccountId = :testAccount.Id];
        System.assertEquals(1, createdContacts.size(), 'Default contact not created for active customer account');

        // Create a test Account with Type = 'Customer' and IsActive = false
        Account testInactiveAccount = new Account(
            Name = 'Test',
            Type = 'Customer - Direct',
            AGActive__c = false
        );
        insert testInactiveAccount;

        // Verify that no default contact is created for inactive customer account
        List<Contact> createdInactiveAccountContacts = [SELECT Id FROM Contact WHERE AccountId = :testInactiveAccount.Id];
        System.assertEquals(0, createdInactiveAccountContacts.size(), 'Default contact created for inactive customer account');
        
        //updating VGActive__c contact should be created
        testInactiveAccount.AGActive__c = true;
        update testInactiveAccount;
        
        
           List<Contact> createdInactiveAccountContact = [SELECT Id FROM Contact WHERE AccountId = :testInactiveAccount.Id];
        System.assertEquals(1, createdInactiveAccountContact.size(), 'Default contact created for inactive customer account');
        
        
        
        
    }
}